services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    image: 'markcloud-casefile-crawling-remind:latest'
    container_name: 'markcloud-casefile-crawling-remind-container'
    restart: always
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env